language: java
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
install: true
script: ./travis/build.sh
env:
  global:
  # REPO_PASSWORD
  - secure: MpH2YhkPU7k6khrY1G+x902MB4p1az5lUgW4fwRziBZCncCUmx6qHAVGe0XlJ8t80R41tV1JBjDdzp4DRmYWBiJR0MHQD4Kld+rwzU7HLM2NHmZhpg3bk12LA70sKze1oc+NDyT4qRkrOODilKu3Y72fS9yNnHNmmEeCJy4rkz2niIcEIOI5EvfXaSgLIxvS3kUrPlmBsrou5f6ZS3q68pQDvEcAMJcT0zelm5u4Ed4dolV6Z7ezJxeM5+7l9I+cnxPDB7WggtdsYTEs9TB30FcqG7QwXR8QP1Lta5CIwJEJUDQ5HHaoJ/8eZHOX9nkC+IHt03+195CmnbUqrRk/1a5YuTRI79ejXkSAWt4TGTUJwHxjRTnc2c5hALFvZfWBHBz3Sl2MTvLwrtFytNgENp/dRik0S2BxGY815npPjkTWNzO0JYeHgTCcqQZ7SMA2/Ws/h/GvRtNW4AoUpRwSY05/eMy/86FpaPf8gJYOI/hzeeO7LknXJsup6LOqWX4ur11IKj3DuHGw4Ec6MEmgEYmO8TX9SJ0AQrcb/Te9MIZPb+ce/hsS9CqwsiOA5ZBnVLa71/L+DonNTupNYyjBp7Xy4NofxgdrkWrIkN7+DVVywQF+KdxBT52M/lNmRS4iG3TgqhIedMKGhJRIMx4IHVJXyFpEUhpfEzsMDCCXPMI=
  # TOMCAT_USERNAME
  - secure: ojn19kLrRjfNGEindivufyogtYVMbUHo5pyQmB5dXd3SojxEUIyYx7o7tYCfFcCQ0AmVZCEwmpU651R/m4cKobbx0suF6epozizhvS93Egc0RR5xXyUAHi0SgEUOf8fsv1V3SYy8gdaqcFFXTg5owtkdnfjjspIqrX8xZoVHItH21g06Izu1Zag+3/ovUrINY6TQM1voMQdBWlLzJ5N/gtY2AfhBGzdqa0tfSrpv23xRu1jrD0jZtE271tCHVlAFM9uJOLOP9nQYBxXC5DAoTgEVZb3yPgyiJgw0vWHneTEF5X+CQ5o7RXJQOWVdLJw5ZKfjLyFyHai44S1TA+x0WvAZjmwQvMlqD3PoTOd8dyz94eRU4lv2FE+bnzLjpBeSwLBl9tk9CketJIaQcOMUUOnuAidvgiKfDkNuMt2q5LcE0qFfjrgY8k8DBtYI13hodGMIIuUP3zXaH4nK2jOfgzVzshCpVk3pwsqtxwDjnTUIFvv8IJO5K5kC6dDlWbH+J7yrX4kPj7GKFxYcdWsjSg59E/qjeeHomqzq7PMj1XqWRgDo4JmqZxU+qgr3f2tabyP8whFdbDZTQgLuX1y0lP+7hUzOwkoi/mnqUAHlj81vRylBcX/gFtI+pJQwD7ZDwLfAmBPrkizetavxTWROnAuOoeRlzseVpclAscM2SEo=
  # TOMCAT_PASSWORD
  - secure: Hwsrlm4AblXCNdW837Z6Omsjw8sRrWA3V5/b+EtFEIzHEQE3Yd+LpKG6nW79QIKNQAwDxWb6YiDd7iFUPXYuPGW30HNvkq0VBUbWetuXF87tz9oJLwTZal8xhAk7LS9P+edf7f22UI1rdMj7nBG8VKTF9zWqm2vWphhJIMJBHIsAlk04qxOgDVPbhiccbJJ7TBpt3sIADmWeD8Z1gl23VolW+u/OELUg0Q+2JA+8RChL6vcju2/uh7pUrkMl3nqMrm8Go6EC6EDvtpOW8jcd5ov76t8opAmU6gfNWE5ZP72s9UHXuHsw+iFyO5QU3LdYMNBYRCisoYCRudy7O8uOEVsD35GaFhZmjAggawHu8FVUrnCAHYla23vEpgwxhyt0tCn9jVNJlViQMrF0S8ph7tQtykv+jpVZa+JZIyQOLDItbTxSnRqNswTEpFqZgYKbXL9DMtnt2rKeJKb48GUY8KTxM7RswczQOJ/X5nA+n2d86kPf8d4etQcXAoyfAzOv7N8JTW2lLnY/AFJpg1sHUnXKOQTNpXxHXJGrT9tHsNVHzY+IOZKqvCsfB0T5IlOslD62OgHGO5V5N9EycKyHON0nCPzFRx+0Ej+pm+leq+WQq4NYCO605qyE+WnA96L8ZiVhTTxQYeqcWxISzi+UTv9o/Mw4tcJJBz8ePmZVkAY=
notifications:
  irc: "irc.rizon.net#runelite"
  webhooks: https://runelite.000webhostapp.com/travis-ci.php
