datasource:
  runelite:
    jndiName: java:comp/env/jdbc/runelite
  runelite-cache:
    jndiName: java:comp/env/jdbc/runelite-cache2

# By default Spring tries to register the datasource as an MXBean,
# so if multiple apis are deployed on one web container with
# shared datasource it tries to register it multiples times and
# fails when starting the 2nd api
spring.jmx.enabled: false

# Google OAuth client
oauth:
  client-id:
  client-secret:
  callback: https://api.runelite.net/oauth/

# Minio client storage for cache
minio:
  endpoint: http://localhost:9000
  accesskey: AM54M27O4WZK65N6F8IP
  secretkey: /PZCxzmsJzwCHYlogcymuprniGCaaLUOET2n6yMP
  bucket: runelite

# Redis client
redis:
  pool.size: 10
  host: tcp://localhost:6379

mongo:
  jndiName: java:comp/env/mongodb/runelite
  database: runelite

runelite:
  # Twitter client for feed
  twitter:
    consumerkey:
    secretkey:
    listid: 1185897074786742273
  ge:
    history: 90 # days
  loottracker:
    history: 90 # days
  wiki:
    poll.ms: 300000 # 5 minutes
    url: https://prices.runescape.wiki/api/v1/osrs/latest
  price:
    cache: 30 # minutes
  feed:
    rssUrl: https://runelite.net/atom.xml
  worlds:
    url: http://www.runescape.com/g=oldscape/slr.ws?order=LPWM
  osrsnews:
    rssUrl: https://services.runescape.com/m=news/latest_news.rss?oldschool=true
  item:
    itemUrl: https://services.runescape.com/m=itemdb_oldschool/api/catalogue/detail.json
    priceUrl: https://services.runescape.com/m=itemdb_oldschool/api/graph